version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: html-example-app
    path: ""
    text-resources:
      - path: "*.html"
        format: html-hardcoded

